### ISSUE TITLE
error: package net.jimmar.unityplugins.PermissionPlease clashes with class of same name

### ISSUE THREAD

**Issue by reddy36996** [Jimmar/Permission-Please#1]
Hi Jimmar,
I came across this plugin through stackoverflow link. Plugin seems to be well implemented but it is throwing error while making gradle build from Unity 2017.3. Seems to be minor issue. Please check:

> Temp\gradleOut\PermissionPlease\build\generated\source\buildConfig\release\net\jimmar\unityplugins\PermissionPlease\BuildConfig.java:4: error: package net.jimmar.unityplugins.PermissionPlease clashes with class of same name
> package net.jimmar.unityplugins.PermissionPlease;

**Comment by Randehh** [comment]
I'm getting the same issue.

**Comment by reddy36996** [comment]
@Randehh 
I was able to resolve this issue by changing Manifest file inside folder Plugins>Android>PermissionPlease 
package="net.jimmar.unityplugins.permissionplease"
to
package="net.jimmar.unityplugins"

i faced one more issue of targetJDK version being old, i had to make jar file again with target jdk version 1.7. Don't know if you will face this issue.

**Comment by Randehh** [comment]
Mm, it will build but it won't work on my phone. It won't find the class this way.

**Comment by phuzik** [comment]
@reddy36996  
Do you still have PermissionPlease.jar version java 1.7?
